machine:
  kubelet:
      nodeIP:
          validSubnets:
              - 10.20.0.0/24
  network:
    hostname: ccs-dev-cp1
    nameservers:
      - 8.8.4.4
      - 8.8.8.8
    interfaces:
      - interface: enp1s0
        addresses:
          - 10.20.0.2/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.20.0.1
        vip:
          ip: 10.20.0.10
  kernel:
    modules:
      - name: br_netfilter
      - name: xt_socket
  sysctls:
    net.ipv4.conf.all.rp_filter: "0"
    net.ipv4.conf.default.rp_filter: "0"
  registries:
    mirrors:
      ghcr.io:
        endpoints:
          - http://10.20.0.1:5000
      registry.k8s.io:
        endpoints:
          - http://10.20.0.1:5000
      docker.io:
        endpoints:
          - http://10.20.0.1:5000
      10.20.0.1:5000:
        endpoints:
          - http://10.20.0.1:5000
cluster:
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: false
            service:
                disabled: false
